digit_number = input("Enter 2 digit number \n")
number1 = int(digit_number[0])
number2 = int(digit_number[1])
output = str(number1 + number2)
print(output)
print(str(number1)+" + "+str(number2)+" = "+output)